vgui_loadout = [[
"resource/ui/vgui_loadout.res"
{
	"vgui_loadout"
	{
		"ControlName"		"Frame"
		"fieldName"		"vgui_loadout"
		"xpos"		"330"
		"ypos"		"312"
		"zpos"		"290"
		"wide"		"364"
		"tall"		"144"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"settitlebarvisible"		"0"
		"title"		"#Frame_Untitled"
		"sizable"		"1"
	}
	"CheckButton1"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"CheckButton1"
		"xpos"		"10"
		"ypos"		"24"
		"zpos"		"290"
		"wide"		"84"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"Steyr AUG"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"CheckButton2"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"CheckButton2"
		"xpos"		"10"
		"ypos"		"44"
		"zpos"		"290"
		"wide"		"84"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"SPAS 12"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"CheckButton3"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"CheckButton3"
		"xpos"		"10"
		"ypos"		"64"
		"zpos"		"290"
		"wide"		"84"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"FN-P90"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"CheckButton4"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"CheckButton4"
		"xpos"		"10"
		"ypos"		"84"
		"zpos"		"290"
		"wide"		"64"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"FA-MAS C"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"CheckButton5"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"CheckButton5"
		"xpos"		"124"
		"ypos"		"24"
		"zpos"		"290"
		"wide"		"104"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"Nighthawk .50"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
		"CheckButton12"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"CheckButton12"
		"xpos"		"124"
		"ypos"		"84"
		"zpos"		"290"
		"wide"		"84"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"Glock 20"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"CheckButton6"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"CheckButton6"
		"xpos"		"124"
		"ypos"		"44"
		"zpos"		"290"
		"wide"		"84"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"Medikit"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"CheckButton7"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"CheckButton7"
		"xpos"		"124"
		"ypos"		"64"
		"zpos"		"290"
		"wide"		"84"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"Tripmine"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"Flashlight"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"Flashlight"
		"xpos"		"252"
		"ypos"		"24"
		"zpos"		"290"
		"wide"		"84"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"NULL"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"CheckButton8"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"CheckButton8"
		"xpos"		"252"
		"ypos"		"44"
		"zpos"		"290"
		"wide"		"84"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"NULL"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"CheckButton9"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"CheckButton9"
		"xpos"		"252"
		"ypos"		"64"
		"zpos"		"290"
		"wide"		"100"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"NULL"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"CheckButton10"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"CheckButton10"
		"xpos"		"252"
		"ypos"		"84"
		"zpos"		"290"
		"wide"		"94"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"NULL"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"FieldIn"
	{
		"ControlName"		"Button"
		"fieldName"		"FieldIn"
		"xpos"		"264"
		"ypos"		"112"
		"zpos"		"290"
		"wide"		"75"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"Ready"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"SelectFieldIn"
		"Default"		"1"
	}
	"Label1"
	{
		"ControlName"		"Label"
		"fieldName"		"Label1"
		"xpos"		"10"
		"ypos"		"0"
		"wide"		"84"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"Paintball Guns"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Divider1"
	{
		"ControlName"		"Divider"
		"fieldName"		"Divider1"
		"xpos"		"114"
		"ypos"		"24"
		"wide"		"2"
		"tall"		"84"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"Label2"
	{
		"ControlName"		"Label"
		"fieldName"		"Label2"
		"xpos"		"124"
		"ypos"		"0"
		"wide"		"84"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"Pods"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Divider2"
	{
		"ControlName"		"Divider"
		"fieldName"		"Divider2"
		"xpos"		"242"
		"ypos"		"24"
		"wide"		"2"
		"tall"		"84"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"Label3"
	{
		"ControlName"		"Label"
		"fieldName"		"Label3"
		"xpos"		"252"
		"ypos"		"0"
		"wide"		"64"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"NULL"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
}
]]
